//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ateik.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Messages : global::System.Configuration.ApplicationSettingsBase {
        
        private static Messages defaultInstance = ((Messages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Messages())));
        
        public static Messages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nepavyko atidaryti paveikslo")]
        public string FailedOpenImageFile {
            get {
                return ((string)(this["FailedOpenImageFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nepavyko išsaugoti paveikslo")]
        public string FailedSaveImageFile {
            get {
                return ((string)(this["FailedSaveImageFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ekrano darbalaukis per mažas")]
        public string DesktopToSmall {
            get {
                return ((string)(this["DesktopToSmall"]));
            }
        }
    }
}
